package com.ossom.monitoring.model;

import lombok.Builder;
import lombok.Data;

import java.time.Instant;

/**
 * The fully enriched alert payload — anomaly + LLM explanation — ready to dispatch.
 */
@Data
@Builder
public class AlertPayload {

    private AnomalyResult anomaly;

    /** One-sentence summary (from LLM or fallback) */
    private String summary;

    /** JSON array string of probable root causes */
    private String rootCauses;

    /** JSON array string of recommended actions */
    private String recommendedActions;

    private Instant firedAt;

    /** Whether this payload was enriched by LLM or generated by rule fallback */
    private boolean llmEnriched;
}
